
APP_DIR = $(subdir)


VPP_FLAGS +=  -I $(UPPER_DIR)/$(APP_DIR)
CPP_FLAGS +=  -I $(UPPER_DIR)/$(APP_DIR)


VPP_FLAGS +=  -I $(UPPER_DIR)/$(APP_DIR)/${COMMON_PATH}
CPP_FLAGS +=  -I $(UPPER_DIR)/$(APP_DIR)/${COMMON_PATH}

